### ISSUE TITLE
Photini doesn't start on Parabola / Arch

### ISSUE THREAD

**Issue by miguelmenendez** [jim-easterbrook/Photini#25]
```
Traceback (most recent call last):
  File "/usr/bin/photini", line 9, in <module>
    load_entry_point('Photini==2016.7.0', 'gui_scripts', 'photini')()
  File "/usr/lib/python3.5/site-packages/photini/editor.py", line 386, in main
    main = MainWindow(options.verbose, args)
  File "/usr/lib/python3.5/site-packages/photini/editor.py", line 141, in __init__
    tab['object'] = tab['class'](self.image_list)
  File "/usr/lib/python3.5/site-packages/photini/photinimap.py", line 114, in __init__
    self.edit_box.lineEdit().returnPressed.connect(self.search)
TypeError: decorated slot has no signature compatible with returnPressed()
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 1881, in shutdown
    h.flush()
  File "/usr/lib/python3.5/logging/__init__.py", line 964, in flush
    self.stream.flush()
  File "/usr/lib/python3.5/site-packages/photini/loggerwindow.py", line 58, in flush
    self.flush_text.emit()
AttributeError: 'StreamProxy' does not have a signal with the signature flush_text()
```

**Comment by miguelmenendez** [comment]
- python 3.5.2
- python-pyqt 5.6
- python-six 1.10.0
- python-appdirs 1.4.0
- libgexiv2 0.10.3
- python-pgi 0.0.11.1
- python-keyring 9.3

**Comment by jim-easterbrook** [comment]
Thanks for reporting this. It appears to be a problem with PyQt 5.6 - I'm still on 5.4 on my main development machine. I'll investigate later on today.

**Comment by jim-easterbrook** [comment]
I've installed Parabola / Arch on a virtual machine (after some false starts) and managed to reproduce the problem. PyQt 5.6 appears to be more fussy about slot signatures than earlier versions. Commit 5c0e027 should fix this particular problem.

Interestingly I'm getting consistent segmentation faults on shutdown (see issue #18) on Arch linux, so maybe it will help in finding that problem.

**Comment by miguelmenendez** [comment]
```
Photini 2016.07.0, build 677 (4947c30)
  Python 3.5.2 (default, Jun 28 2016, 08:45:52) 
[GCC 6.1.1 20160602]
  PyGI 3.20.0, GExiv2 0.10, GObject 2.0
  PyQt 5.6, Qt 5.6.0

It works now.
