### ISSUE TITLE
Google Photo Crash

### ISSUE THREAD

**Issue by HydrelioxGitHub** [jim-easterbrook/Photini#50]
I've just installed Photini and signin my Google account to upload some photos. But when I go to the Google photo tab, I can see my Google profile picture but nothing else is clickable except "Log in" and I have a window with this log : 

```
18:05:22: ERROR: photini.pyqt: 'title'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\pyqt.py", line 113, in wrapper
    return func(*args, **kwds)
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\uploader.py", line 274, in connection_changed
    self.show_album_list(self.session.get_albums())
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\googlephotos.py", line 323, in show_album_list
    self.upload_config.add_album(album)
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\googlephotos.py", line 267, in add_album
    widget = QtWidgets.QCheckBox(album['title'].replace('&', '&&'))
KeyError: 'title'
18:07:56: ERROR: photini.pyqt: 'title'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\pyqt.py", line 113, in wrapper
    return func(*args, **kwds)
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\uploader.py", line 274, in connection_changed
    self.show_album_list(self.session.get_albums())
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\googlephotos.py", line 323, in show_album_list
    self.upload_config.add_album(album)
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\googlephotos.py", line 267, in add_album
    widget = QtWidgets.QCheckBox(album['title'].replace('&', '&&'))
KeyError: 'title'
18:08:05: ERROR: photini.pyqt: 'title'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\pyqt.py", line 113, in wrapper
    return func(*args, **kwds)
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\uploader.py", line 274, in connection_changed
    self.show_album_list(self.session.get_albums())
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\googlephotos.py", line 323, in show_album_list
    self.upload_config.add_album(album)
  File "C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini\googlephotos.py", line 267, in add_album
    widget = QtWidgets.QCheckBox(album['title'].replace('&', '&&'))
KeyError: 'title'
```

I use the last all in one windows installer version (2019.10.0)

**Comment by jim-easterbrook** [comment]
Hmm, it appears that one or more of your existing albums on Google Photos doesn't have a title. I didn't know that could happen - when I create one and don't specify a title it gets "Untitled".

**Comment by HydrelioxGitHub** [comment]
I've tried a few month ago a docker container to sync local folders and album in Google Photo. Maybe it had some bug in it and created in some way albums with empty title... 🤔

**Comment by jim-easterbrook** [comment]
It's still something I need to allow for though. I hope I can do a new release within the next few days.

**Comment by HydrelioxGitHub** [comment]
For now, I'll check for theses albums and try to add a title to get the software works. Thank you for your help and your time.

**Comment by jim-easterbrook** [comment]
If possible I'd like you to edit the file `googlephotos.py` that's part of your Photini installation so we can find out what else is missing from these albums (and should I ignore them or substitute default values?).

If you can edit the file, go to line 151 and change
```
            for album in rsp['albums']:
                yield album
```
to
```
            for album in rsp['albums']:
                if 'title' not in album:
                    album['title'] = ''
                yield album
```

**Comment by HydrelioxGitHub** [comment]
Ok, I'll report what the change do as soon as I can.

**Comment by jim-easterbrook** [comment]
Now I've started up my Windows virtual machine I can tell you the file is probably in `C:\Program Files (x86)\Photini\msys2\mingw64\lib\python3.7\site-packages\photini`.

**Comment by HydrelioxGitHub** [comment]
Well, with the little chunk of code there is no more error logging. I have the list of all my albums on Google Photo. One of them is empty. 
I suppose it's normal that I can't upload files to albums not created with Photini (API limitation) but only on albums created with the software.

**Comment by jim-easterbrook** [comment]
Thanks for that - I wanted reassurance that there was nothing else odd about the album list.

The very restricted API Google introduced a while ago makes the uploader far less useful than it once was I'm afraid. I don't understand why they did it, but I'm not in their business.

**Comment by jim-easterbrook** [comment]
Releases 2020.10.0 and after include this fix.
